// Honda 2-Wheeler Product Catalog Seed Data
// Prices are approximate ex-showroom Delhi (INR)
// Images from Honda Sitecore CDN

const HONDA_CDN = "https://edge.sitecorecloud.io/hondamotorc388f-hmsi8ece-prodb777-e813/media/Project/HONDA2WI/honda2wheelersindia";

export interface SeedProduct {
  name: string;
  category: "ev" | "motorcycle" | "scooter";
  subSegment?: string;
  tagline?: string;
  description?: string;
  basePrice: number;
  heroImage?: string;
  colorVariants: { name: string; hexCode: string; imageUrl?: string }[];
  specifications: { key: string; value: string }[];
  features: { title: string; description?: string }[];
  trims: { name: string; priceDiff: number }[];
  sortOrder: number;
}

export const hondaProducts: SeedProduct[] = [
  // ═══════════════════════════════════════
  // EV
  // ═══════════════════════════════════════
  {
    name: "Activa e:",
    category: "ev",
    tagline: "The Future of Riding",
    description: "Honda's first electric scooter for India with swappable battery technology.",
    basePrice: 119445,
    heroImage: `${HONDA_CDN}/menu/Scooter--EV/activa-e.jpg`,
    colorVariants: [
      { name: "Pearl Deep Ground Gray", hexCode: "#4A4A4A" },
      { name: "Matt Axis Gray Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Matt Laurel Green Metallic", hexCode: "#5C7A5C" },
      { name: "Pearl Campanula Blue", hexCode: "#4169A8" },
    ],
    specifications: [
      { key: "Motor Type", value: "PMSM Hub Motor" },
      { key: "Max Power", value: "6 kW" },
      { key: "Battery", value: "Swappable Li-ion 1.5 kWh" },
      { key: "Range", value: "102 km (IDC)" },
      { key: "Charging Time", value: "~5 hrs (portable), Battery Swap" },
      { key: "Kerb Weight", value: "104 kg" },
      { key: "Top Speed", value: "80 km/h" },
      { key: "Brakes (Front)", value: "Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Honda Mobile Power Pack e: Swappable Battery" },
      { title: "TFT Display with Bluetooth Connectivity" },
      { title: "Dual Riding Modes - Standard & Sport" },
      { title: "Regenerative Braking" },
      { title: "LED Headlamp & Tail Lamp" },
    ],
    trims: [],
    sortOrder: 0,
  },
  {
    name: "QC1",
    category: "ev",
    tagline: "Quick. Convenient. One.",
    description: "Honda's affordable electric scooter with fixed battery design.",
    basePrice: 90001,
    heroImage: `${HONDA_CDN}/menu/Scooter--EV/qc1.jpg`,
    colorVariants: [
      { name: "Pearl Siren Blue", hexCode: "#2E5090" },
      { name: "Matt Axis Gray Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Sports Red", hexCode: "#CC0000" },
    ],
    specifications: [
      { key: "Motor Type", value: "Brushless DC Hub Motor" },
      { key: "Max Power", value: "1.2 kW" },
      { key: "Battery", value: "Fixed Li-ion 1.44 kWh" },
      { key: "Range", value: "80 km (IDC)" },
      { key: "Charging Time", value: "~4.5 hrs" },
      { key: "Kerb Weight", value: "81 kg" },
      { key: "Top Speed", value: "50 km/h" },
      { key: "Brakes (Front)", value: "Drum with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Lightweight and Compact Design" },
      { title: "Digital Meter with Charge & Range Indicator" },
      { title: "USB Type-C Charging Port" },
      { title: "LED Headlamp" },
      { title: "Boot Light" },
    ],
    trims: [],
    sortOrder: 1,
  },

  // ═══════════════════════════════════════
  // SCOOTER
  // ═══════════════════════════════════════
  {
    name: "Activa 110",
    category: "scooter",
    tagline: "Desh Ki Dhadkan",
    description: "India's best-selling scooter. Reliable, fuel-efficient and comfortable.",
    basePrice: 75433,
    heroImage: `${HONDA_CDN}/menu/Scooter--EV/activa110.jpg`,
    colorVariants: [
      { name: "Pearl Precious White", hexCode: "#F5F5F0" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Siren Blue", hexCode: "#2E5090" },
      { name: "Pearl Spartan Red", hexCode: "#8B1A1A" },
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "Rebel Red Metallic", hexCode: "#CC3333" },
    ],
    specifications: [
      { key: "Engine", value: "109.51 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "5.9 kW @ 7500 rpm" },
      { key: "Max Torque", value: "8.94 Nm @ 5500 rpm" },
      { key: "Mileage", value: "60 km/l" },
      { key: "Fuel Tank", value: "5.3 L" },
      { key: "Kerb Weight", value: "107 kg" },
      { key: "Transmission", value: "Automatic (CVT)" },
      { key: "Brakes (Front)", value: "Drum / Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Honda Smart Key (DLX)" },
      { title: "Silent Start with ACG" },
      { title: "LED Headlamp" },
      { title: "18L Under-seat Storage" },
      { title: "Integrated Headlamp Beam & Engine Start/Stop Switch" },
    ],
    trims: [
      { name: "Standard - Drum", priceDiff: 0 },
      { name: "Standard - Disc", priceDiff: 6000 },
      { name: "DLX", priceDiff: 8500 },
    ],
    sortOrder: 10,
  },
  {
    name: "Dio 110",
    category: "scooter",
    tagline: "Let's Get Moving",
    description: "Sporty and stylish scooter with youthful design for urban riders.",
    basePrice: 70159,
    heroImage: `${HONDA_CDN}/menu/Scooter--EV/dio110.jpg`,
    colorVariants: [
      { name: "Sports Red", hexCode: "#CC0000" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Vibrant Blue", hexCode: "#0066CC" },
      { name: "Pearl Precious White", hexCode: "#F5F5F0" },
    ],
    specifications: [
      { key: "Engine", value: "109.51 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "5.9 kW @ 7500 rpm" },
      { key: "Max Torque", value: "8.94 Nm @ 5500 rpm" },
      { key: "Mileage", value: "60 km/l" },
      { key: "Fuel Tank", value: "5.3 L" },
      { key: "Kerb Weight", value: "105 kg" },
      { key: "Transmission", value: "Automatic (CVT)" },
      { key: "Brakes (Front)", value: "Drum / Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Digital Meter" },
      { title: "LED Headlamp" },
      { title: "Stylish Dual-Tone Colours" },
      { title: "External Fuel Lid" },
      { title: "Integrated Headlamp Beam & Engine Start/Stop Switch" },
    ],
    trims: [
      { name: "Standard - Drum", priceDiff: 0 },
      { name: "Standard - Disc", priceDiff: 5500 },
    ],
    sortOrder: 11,
  },
  {
    name: "Activa 125",
    category: "scooter",
    tagline: "Premium Style. Premium Comfort.",
    description: "Premium 125cc scooter with advanced features and refined performance.",
    basePrice: 89256,
    heroImage: `${HONDA_CDN}/menu/Scooter--EV/activa125.jpg`,
    colorVariants: [
      { name: "Pearl Precious White", hexCode: "#F5F5F0" },
      { name: "Matt Magnificent Blue Metallic", hexCode: "#2E4A7A" },
      { name: "Pearl Siren Blue", hexCode: "#2E5090" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "Pearl Spartan Red", hexCode: "#8B1A1A" },
    ],
    specifications: [
      { key: "Engine", value: "123.92 cc, Air-cooled, 4-Stroke, SI, eSP+" },
      { key: "Max Power", value: "6.0 kW @ 6500 rpm" },
      { key: "Max Torque", value: "10.4 Nm @ 5000 rpm" },
      { key: "Mileage", value: "56 km/l" },
      { key: "Fuel Tank", value: "5.3 L" },
      { key: "Kerb Weight", value: "111 kg" },
      { key: "Transmission", value: "Automatic (CVT)" },
      { key: "Brakes (Front)", value: "Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Honda Smart Key" },
      { title: "Digital Analogue Meter" },
      { title: "LED Headlamp & Position Lamp" },
      { title: "Idling Stop System" },
      { title: "Silent Start with ACG" },
    ],
    trims: [
      { name: "Drum", priceDiff: 0 },
      { name: "Disc", priceDiff: 5500 },
      { name: "DLX", priceDiff: 9000 },
    ],
    sortOrder: 12,
  },
  {
    name: "Dio 125",
    category: "scooter",
    tagline: "Born To Lead",
    description: "The sportier 125cc Dio with disc brake, H-Smart and digital meter.",
    basePrice: 86733,
    heroImage: `${HONDA_CDN}/scooter/dio125/banner/DIO125.jpg`,
    colorVariants: [
      { name: "Matt Marvel Blue Metallic", hexCode: "#2A4F8A" },
      { name: "Mat Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Sports Red", hexCode: "#CC0000" },
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Pearl Precious White", hexCode: "#F5F5F0" },
    ],
    specifications: [
      { key: "Engine", value: "123.92 cc, Air-cooled, 4-Stroke, SI, eSP+" },
      { key: "Max Power", value: "6.0 kW @ 6500 rpm" },
      { key: "Max Torque", value: "10.4 Nm @ 5000 rpm" },
      { key: "Mileage", value: "55 km/l" },
      { key: "Fuel Tank", value: "5.3 L" },
      { key: "Kerb Weight", value: "111 kg" },
      { key: "Transmission", value: "Automatic (CVT)" },
      { key: "Brakes (Front)", value: "Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Honda Smart Key with Answer Back & Seat Opener" },
      { title: "Fully Digital Meter" },
      { title: "Idling Stop System" },
      { title: "LED Headlamp" },
      { title: "Silent Start with ACG" },
    ],
    trims: [
      { name: "Standard", priceDiff: 0 },
      { name: "H-Smart", priceDiff: 5000 },
    ],
    sortOrder: 13,
  },

  // ═══════════════════════════════════════
  // MOTORCYCLE - RedWing
  // ═══════════════════════════════════════
  {
    name: "Shine 100",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Shine Brighter",
    description: "Honda's most affordable commuter motorcycle with great mileage.",
    basePrice: 65243,
    heroImage: `${HONDA_CDN}/menu/RedWing/shine-100.jpg`,
    colorVariants: [
      { name: "Athletic Blue Metallic", hexCode: "#2E5090" },
      { name: "Black", hexCode: "#1A1A1A" },
      { name: "Grey", hexCode: "#6B6B6B" },
      { name: "Red", hexCode: "#CC0000" },
    ],
    specifications: [
      { key: "Engine", value: "99.7 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "5.6 kW @ 7500 rpm" },
      { key: "Max Torque", value: "8.05 Nm @ 5500 rpm" },
      { key: "Mileage", value: "65 km/l" },
      { key: "Fuel Tank", value: "9.5 L" },
      { key: "Kerb Weight", value: "106 kg" },
      { key: "Transmission", value: "4-Speed" },
      { key: "Brakes (Front)", value: "Drum with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "eSP (enhanced Smart Power) Technology" },
      { title: "Long Stroke Engine for Better Mileage" },
      { title: "5-Step Adjustable Rear Suspension" },
      { title: "DC Headlamp" },
      { title: "Tubeless Tyres" },
    ],
    trims: [
      { name: "Drum - Self Start", priceDiff: 0 },
    ],
    sortOrder: 20,
  },
  {
    name: "Livo",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Live the Livo Life",
    description: "Feature-rich 110cc commuter with comfortable ride and great mileage.",
    basePrice: 79555,
    heroImage: `${HONDA_CDN}/menu/RedWing/Livo.jpg`,
    colorVariants: [
      { name: "Athletic Blue Metallic", hexCode: "#2E5090" },
      { name: "Black", hexCode: "#1A1A1A" },
      { name: "Matte Axis Grey", hexCode: "#6B6B6B" },
      { name: "Imperial Red Metallic", hexCode: "#8B0000" },
    ],
    specifications: [
      { key: "Engine", value: "109.51 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "6.0 kW @ 7500 rpm" },
      { key: "Max Torque", value: "9.30 Nm @ 5000 rpm" },
      { key: "Mileage", value: "60 km/l" },
      { key: "Fuel Tank", value: "9.1 L" },
      { key: "Kerb Weight", value: "113 kg" },
      { key: "Transmission", value: "4-Speed" },
      { key: "Brakes (Front)", value: "Drum with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "eSP Technology" },
      { title: "DC Headlamp" },
      { title: "Tubeless Tyres" },
      { title: "5-Step Adjustable Rear Suspension" },
      { title: "Engine Start/Stop Switch" },
    ],
    trims: [
      { name: "Drum", priceDiff: 0 },
      { name: "Disc", priceDiff: 6000 },
    ],
    sortOrder: 21,
  },
  {
    name: "Shine 125",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Hamesha Aage",
    description: "India's favourite 125cc motorcycle with refined engine and premium styling.",
    basePrice: 81794,
    heroImage: `${HONDA_CDN}/menu/RedWing/shine-125.jpg`,
    colorVariants: [
      { name: "Black", hexCode: "#1A1A1A" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Athletic Blue Metallic", hexCode: "#2E5090" },
      { name: "Imperial Red Metallic", hexCode: "#8B0000" },
      { name: "Pearl Precious White", hexCode: "#F5F5F0" },
    ],
    specifications: [
      { key: "Engine", value: "123.94 cc, Air-cooled, 4-Stroke, SI, eSP" },
      { key: "Max Power", value: "7.8 kW @ 7500 rpm" },
      { key: "Max Torque", value: "10.9 Nm @ 4500 rpm" },
      { key: "Mileage", value: "55 km/l" },
      { key: "Fuel Tank", value: "10.5 L" },
      { key: "Kerb Weight", value: "117 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "eSP Technology" },
      { title: "Silent Start with ACG" },
      { title: "DC Headlamp" },
      { title: "Digital-Analogue Meter" },
      { title: "5-Step Adjustable Rear Suspension" },
    ],
    trims: [
      { name: "Drum", priceDiff: 0 },
      { name: "Disc", priceDiff: 5000 },
    ],
    sortOrder: 22,
  },
  {
    name: "SP 125",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "All-Rounder Supremacy",
    description: "Sporty 125cc motorcycle with full-digital meter and disc brake.",
    basePrice: 87878,
    heroImage: `${HONDA_CDN}/menu/RedWing/sp-125.jpg`,
    colorVariants: [
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Siren Blue", hexCode: "#2E5090" },
      { name: "Pearl Spartan Red", hexCode: "#8B1A1A" },
      { name: "Black", hexCode: "#1A1A1A" },
      { name: "Imperial Red Metallic", hexCode: "#CC2222" },
    ],
    specifications: [
      { key: "Engine", value: "123.94 cc, Air-cooled, 4-Stroke, SI, eSP" },
      { key: "Max Power", value: "7.9 kW @ 7500 rpm" },
      { key: "Max Torque", value: "10.9 Nm @ 4500 rpm" },
      { key: "Mileage", value: "55 km/l" },
      { key: "Fuel Tank", value: "10.5 L" },
      { key: "Kerb Weight", value: "118 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc with CBS" },
      { key: "Brakes (Rear)", value: "Drum with CBS" },
    ],
    features: [
      { title: "Full-Digital Meter" },
      { title: "eSP Technology" },
      { title: "LED Headlamp" },
      { title: "Engine Start/Stop Switch" },
      { title: "5-Step Adjustable Rear Suspension" },
    ],
    trims: [
      { name: "Drum", priceDiff: 0 },
      { name: "Disc", priceDiff: 5000 },
      { name: "Disc (Sports Edition)", priceDiff: 8000 },
    ],
    sortOrder: 23,
  },
  {
    name: "CB125 Hornet",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Street Fighter",
    description: "Sporty 125cc street-naked with full-color TFT display and Bluetooth connectivity.",
    basePrice: 114415,
    heroImage: `${HONDA_CDN}/motorcycle/CB-125/nav/CB125.jpg`,
    colorVariants: [
      { name: "Pearl Siren Blue with Sports Red", hexCode: "#2E5A88" },
      { name: "Pearl Siren Blue with Athletic Blue Metallic", hexCode: "#1C6EA4" },
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Pearl Siren Blue with Lemon Ice Yellow", hexCode: "#FFF44F" },
    ],
    specifications: [
      { key: "Engine", value: "123.94 cc, Air-cooled, 4-Stroke, SI, BS6 OBD2B" },
      { key: "Max Power", value: "10.99 bhp" },
      { key: "Max Torque", value: "11.2 Nm" },
      { key: "Mileage", value: "55 km/l" },
      { key: "Fuel Tank", value: "12 L" },
      { key: "Kerb Weight", value: "124 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc with Single-Channel ABS" },
      { key: "Brakes (Rear)", value: "Drum" },
    ],
    features: [
      { title: "Full-Color TFT Display with Bluetooth" },
      { title: "LED Headlamp & Tail Lamp" },
      { title: "Single-Channel ABS" },
      { title: "Assist & Slipper Clutch" },
      { title: "Sporty Split Seat" },
    ],
    trims: [],
    sortOrder: 23,
  },
  {
    name: "CB200X",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Go. X-plore.",
    description: "Adventure-styled motorcycle with upright riding position and capable engine.",
    basePrice: 147000,
    heroImage: undefined, // CB200X discontinued from Honda India website
    colorVariants: [
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "Matt Selene Silver Metallic", hexCode: "#C0C0C0" },
      { name: "Matt Marvel Blue Metallic", hexCode: "#2A4F8A" },
    ],
    specifications: [
      { key: "Engine", value: "184.4 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "12.7 kW @ 8500 rpm" },
      { key: "Max Torque", value: "16.1 Nm @ 6000 rpm" },
      { key: "Mileage", value: "42 km/l" },
      { key: "Fuel Tank", value: "12.2 L" },
      { key: "Kerb Weight", value: "145 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc" },
      { key: "Brakes (Rear)", value: "Disc" },
    ],
    features: [
      { title: "Full-Digital LCD Meter" },
      { title: "LED Headlamp" },
      { title: "Golden USD Front Forks" },
      { title: "Dual-Channel ABS" },
      { title: "Long Travel Suspension" },
    ],
    trims: [],
    sortOrder: 24,
  },
  {
    name: "Unicorn",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Everyone's First Choice",
    description: "Premium 160cc commuter motorcycle trusted for its reliability and performance.",
    basePrice: 112898,
    heroImage: `${HONDA_CDN}/menu/RedWing/Unicorn.jpg`,
    colorVariants: [
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Siren Blue", hexCode: "#2E5090" },
      { name: "Imperial Red Metallic", hexCode: "#8B0000" },
    ],
    specifications: [
      { key: "Engine", value: "162.71 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "9.6 kW @ 7000 rpm" },
      { key: "Max Torque", value: "14.0 Nm @ 4500 rpm" },
      { key: "Mileage", value: "50 km/l" },
      { key: "Fuel Tank", value: "12.0 L" },
      { key: "Kerb Weight", value: "138 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc" },
      { key: "Brakes (Rear)", value: "Drum" },
    ],
    features: [
      { title: "eSP Technology" },
      { title: "Full-Digital Meter" },
      { title: "LED Headlamp" },
      { title: "Silent Start with ACG" },
      { title: "Tubeless Tyres" },
    ],
    trims: [],
    sortOrder: 25,
  },
  {
    name: "SP 160",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Next-Level Performance",
    description: "Sporty 160cc motorcycle with advanced features and aggressive styling.",
    basePrice: 115556,
    heroImage: `${HONDA_CDN}/menu/RedWing/sp-160.jpg`,
    colorVariants: [
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
      { name: "Pearl Siren Blue", hexCode: "#2E5090" },
      { name: "Sports Red", hexCode: "#CC0000" },
      { name: "Matt Marvel Blue Metallic", hexCode: "#2A4F8A" },
    ],
    specifications: [
      { key: "Engine", value: "162.71 cc, Air-cooled, 4-Stroke, SI, eSP+" },
      { key: "Max Power", value: "10.2 kW @ 7500 rpm" },
      { key: "Max Torque", value: "14.7 Nm @ 5500 rpm" },
      { key: "Mileage", value: "50 km/l" },
      { key: "Fuel Tank", value: "12.0 L" },
      { key: "Kerb Weight", value: "140 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc" },
      { key: "Brakes (Rear)", value: "Drum / Disc" },
    ],
    features: [
      { title: "Full-Digital LCD Meter" },
      { title: "eSP+ Technology" },
      { title: "LED Headlamp" },
      { title: "Rear Disc Brake (DLX variant)" },
      { title: "Single Channel ABS" },
    ],
    trims: [
      { name: "Single Disc", priceDiff: 0 },
      { name: "DLX (Dual Disc)", priceDiff: 6000 },
    ],
    sortOrder: 26,
  },
  {
    name: "NX200",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Ride the Adventure",
    description: "Adventure motorcycle for daily commutes and weekend trails.",
    basePrice: 157748,
    heroImage: `${HONDA_CDN}/menu/RedWing/NX200.jpg`,
    colorVariants: [
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "Matt Selene Silver Metallic", hexCode: "#C0C0C0" },
      { name: "Pearl Spartan Red", hexCode: "#8B1A1A" },
    ],
    specifications: [
      { key: "Engine", value: "184.4 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "12.7 kW @ 8500 rpm" },
      { key: "Max Torque", value: "16.1 Nm @ 6000 rpm" },
      { key: "Mileage", value: "42 km/l" },
      { key: "Fuel Tank", value: "12.0 L" },
      { key: "Kerb Weight", value: "148 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc" },
      { key: "Brakes (Rear)", value: "Disc" },
    ],
    features: [
      { title: "Full-Digital LCD Meter" },
      { title: "LED Headlamp" },
      { title: "Dual-Channel ABS" },
      { title: "Long Travel Suspension" },
      { title: "Knuckle Cover" },
    ],
    trims: [],
    sortOrder: 27,
  },
  {
    name: "Hornet 2.0",
    category: "motorcycle",
    subSegment: "RedWing",
    tagline: "Born to Lead",
    description: "Aggressive street-naked motorcycle with muscular styling.",
    basePrice: 147151,
    heroImage: `${HONDA_CDN}/menu/RedWing/Hornet.jpg`,
    colorVariants: [
      { name: "Pearl Igneous Black", hexCode: "#1A1A1A" },
      { name: "Repsol Racing Edition", hexCode: "#FF6600" },
      { name: "Matt Marvel Blue Metallic", hexCode: "#2A4F8A" },
      { name: "Sports Red", hexCode: "#CC0000" },
    ],
    specifications: [
      { key: "Engine", value: "184.4 cc, Air-cooled, 4-Stroke, SI" },
      { key: "Max Power", value: "12.7 kW @ 8500 rpm" },
      { key: "Max Torque", value: "16.1 Nm @ 6000 rpm" },
      { key: "Mileage", value: "42 km/l" },
      { key: "Fuel Tank", value: "12.0 L" },
      { key: "Kerb Weight", value: "142 kg" },
      { key: "Transmission", value: "5-Speed" },
      { key: "Brakes (Front)", value: "Disc" },
      { key: "Brakes (Rear)", value: "Disc" },
    ],
    features: [
      { title: "Full-Digital Negative LCD Meter" },
      { title: "LED Headlamp & Tail Lamp" },
      { title: "Golden USD Front Forks" },
      { title: "Dual-Channel ABS" },
      { title: "Underbelly Exhaust" },
    ],
    trims: [],
    sortOrder: 28,
  },

  // ═══════════════════════════════════════
  // MOTORCYCLE - BigWing
  // ═══════════════════════════════════════
  {
    name: "CB300F",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "The Fun Machine",
    description: "Lightweight 300cc Flex-Fuel streetfighter designed for fun and agility.",
    basePrice: 155658,
    heroImage: `${HONDA_CDN}/menu/BigWing/CB300F.jpg`,
    colorVariants: [
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "Matt Gunpowder Black Metallic", hexCode: "#333333" },
      { name: "Matt Marvel Blue Metallic", hexCode: "#2A4F8A" },
    ],
    specifications: [
      { key: "Engine", value: "293.52 cc, Liquid-cooled, 4-Stroke, DOHC, SI" },
      { key: "Max Power", value: "18.3 kW @ 7500 rpm" },
      { key: "Max Torque", value: "25.6 Nm @ 5500 rpm" },
      { key: "Fuel Tank", value: "14.1 L" },
      { key: "Kerb Weight", value: "153 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "Disc" },
      { key: "Brakes (Rear)", value: "Disc" },
    ],
    features: [
      { title: "Full-Digital LCD Meter" },
      { title: "LED Headlamp & Tail Lamp" },
      { title: "Dual-Channel ABS" },
      { title: "Assist & Slipper Clutch" },
      { title: "Golden USD Front Forks" },
    ],
    trims: [],
    sortOrder: 30,
  },
  {
    name: "CB300R",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Neo Sports Cafe",
    description: "Neo Sports Cafe-styled 300cc motorcycle with retro-modern design.",
    basePrice: 250000,
    heroImage: `${HONDA_CDN}/menu/BigWing/CB300R.jpg`,
    colorVariants: [
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "Candy Chromosphere Red", hexCode: "#CC2222" },
      { name: "Matt Axis Grey Metallic", hexCode: "#6B6B6B" },
    ],
    specifications: [
      { key: "Engine", value: "286.01 cc, Liquid-cooled, 4-Stroke, DOHC" },
      { key: "Max Power", value: "23.5 kW @ 9000 rpm" },
      { key: "Max Torque", value: "27.5 Nm @ 7500 rpm" },
      { key: "Fuel Tank", value: "10 L" },
      { key: "Kerb Weight", value: "144 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "296mm Disc, ABS" },
      { key: "Brakes (Rear)", value: "220mm Disc, ABS" },
    ],
    features: [
      { title: "IMU-Based Dual-Channel ABS" },
      { title: "Full-Digital LCD Meter" },
      { title: "LED Headlamp & Tail Lamp" },
      { title: "Assist & Slipper Clutch" },
      { title: "USD Forks with Preload Adjustability" },
    ],
    trims: [],
    sortOrder: 31,
  },
  {
    name: "CB350",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Make Memories",
    description: "Modern classic motorcycle with timeless design and refined performance.",
    basePrice: 197015,
    heroImage: `${HONDA_CDN}/menu/BigWing/CB350-menu.jpg`,
    colorVariants: [
      { name: "Pearl Nightstar Black", hexCode: "#1A1A1A" },
      { name: "DLX Pro - Precious Black Metallic", hexCode: "#2A2A2A" },
      { name: "Matt Marshal Green Metallic", hexCode: "#3A5A3A" },
      { name: "Candy Chromosphere Red", hexCode: "#CC2222" },
      { name: "Pearl Deep Mud Gray", hexCode: "#5A5A5A" },
    ],
    specifications: [
      { key: "Engine", value: "348.36 cc, Air-cooled, 4-Stroke, SOHC, SI" },
      { key: "Max Power", value: "15.5 kW @ 5500 rpm" },
      { key: "Max Torque", value: "30 Nm @ 3000 rpm" },
      { key: "Fuel Tank", value: "15.0 L" },
      { key: "Kerb Weight", value: "181 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "310mm Disc" },
      { key: "Brakes (Rear)", value: "240mm Disc" },
    ],
    features: [
      { title: "Honda Selectable Torque Control (HSTC)" },
      { title: "Dual-Channel ABS" },
      { title: "Assist & Slipper Clutch" },
      { title: "LED Headlamp" },
      { title: "Honda Smartphone Voice Control" },
    ],
    trims: [
      { name: "Standard", priceDiff: 0 },
      { name: "DLX", priceDiff: 6000 },
      { name: "DLX Pro", priceDiff: 12000 },
    ],
    sortOrder: 32,
  },
  {
    name: "CB350RS",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Roadster Rebel",
    description: "Scrambler-styled variant of CB350 with sporty attitude.",
    basePrice: 197414,
    heroImage: `${HONDA_CDN}/menu/BigWing/CB350RS.jpg`,
    colorVariants: [
      { name: "Radiant Red Metallic", hexCode: "#CC2222" },
      { name: "Black with Red Highlights", hexCode: "#1A1A1A" },
      { name: "Matte Massive Grey Metallic", hexCode: "#5A5A5A" },
    ],
    specifications: [
      { key: "Engine", value: "348.36 cc, Air-cooled, 4-Stroke, SOHC, SI" },
      { key: "Max Power", value: "15.5 kW @ 5500 rpm" },
      { key: "Max Torque", value: "30 Nm @ 3000 rpm" },
      { key: "Fuel Tank", value: "15.0 L" },
      { key: "Kerb Weight", value: "179 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "310mm Disc" },
      { key: "Brakes (Rear)", value: "240mm Disc" },
    ],
    features: [
      { title: "Honda Selectable Torque Control (HSTC)" },
      { title: "Dual-Channel ABS" },
      { title: "Assist & Slipper Clutch" },
      { title: "LED Headlamp & Tail Lamp" },
      { title: "Scrambler-Style Exhaust" },
    ],
    trims: [],
    sortOrder: 33,
  },
  {
    name: "NX500",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Born to Explore",
    description: "Mid-size adventure touring motorcycle for long-distance exploration.",
    basePrice: 632126,
    heroImage: `${HONDA_CDN}/menu/BigWing/NX500.jpg`,
    colorVariants: [
      { name: "Pearl Organic Green", hexCode: "#4A6A4A" },
      { name: "Matt Gunpowder Black Metallic", hexCode: "#333333" },
      { name: "Grand Prix Red", hexCode: "#CC0000" },
    ],
    specifications: [
      { key: "Engine", value: "471 cc, Liquid-cooled, 4-Stroke, 8-Valve, DOHC, Parallel-Twin" },
      { key: "Max Power", value: "35.2 kW @ 8600 rpm" },
      { key: "Max Torque", value: "43.4 Nm @ 6500 rpm" },
      { key: "Fuel Tank", value: "17.5 L" },
      { key: "Kerb Weight", value: "192 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "310mm Disc" },
      { key: "Brakes (Rear)", value: "240mm Disc" },
    ],
    features: [
      { title: "5\" TFT Multi-Information Display" },
      { title: "Honda Selectable Torque Control (HSTC)" },
      { title: "Dual-Channel ABS" },
      { title: "USB Type-C Charging" },
      { title: "Assist & Slipper Clutch" },
    ],
    trims: [],
    sortOrder: 34,
  },
  {
    name: "CB650R",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Neo Sports Cafe",
    description: "Inline-four 650cc naked sport motorcycle with E-Clutch and aggressive styling.",
    basePrice: 1028640,
    heroImage: `${HONDA_CDN}/menu/BigWing/CB650R-new.png`,
    colorVariants: [
      { name: "Matt Gunpowder Black Metallic", hexCode: "#333333" },
      { name: "Candy Chromosphere Red", hexCode: "#CC2222" },
    ],
    specifications: [
      { key: "Engine", value: "648.72 cc, Liquid-cooled, 4-Stroke, DOHC, Inline-4" },
      { key: "Max Power", value: "63.3 kW @ 11000 rpm" },
      { key: "Max Torque", value: "57.5 Nm @ 8000 rpm" },
      { key: "Fuel Tank", value: "15.4 L" },
      { key: "Kerb Weight", value: "202 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "Dual 310mm Discs" },
      { key: "Brakes (Rear)", value: "240mm Disc" },
    ],
    features: [
      { title: "Full-Digital TFT Display" },
      { title: "LED All-Around Lighting" },
      { title: "Ride-by-Wire Throttle" },
      { title: "Honda Selectable Torque Control" },
      { title: "Assist & Slipper Clutch" },
    ],
    trims: [],
    sortOrder: 35,
  },
  {
    name: "CBR650R",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Total Control",
    description: "Inline-four sport motorcycle with full fairing, E-Clutch for track-inspired riding.",
    basePrice: 1114362,
    heroImage: `${HONDA_CDN}/menu/BigWing/CBR650R-new.png`,
    colorVariants: [
      { name: "Grand Prix Red", hexCode: "#CC0000" },
      { name: "Matt Gunpowder Black Metallic", hexCode: "#333333" },
    ],
    specifications: [
      { key: "Engine", value: "648.72 cc, Liquid-cooled, 4-Stroke, DOHC, Inline-4" },
      { key: "Max Power", value: "63.3 kW @ 11000 rpm" },
      { key: "Max Torque", value: "57.5 Nm @ 8000 rpm" },
      { key: "Fuel Tank", value: "15.4 L" },
      { key: "Kerb Weight", value: "208 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "Dual 310mm Discs" },
      { key: "Brakes (Rear)", value: "240mm Disc" },
    ],
    features: [
      { title: "Full-Digital TFT Display" },
      { title: "LED All-Around Lighting" },
      { title: "Showa SFF-BP Front Forks" },
      { title: "Honda Selectable Torque Control" },
      { title: "Emergency Stop Signal" },
    ],
    trims: [],
    sortOrder: 36,
  },
  {
    name: "XL750 Transalp",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "Go Beyond",
    description: "Legendary adventure tourer reborn with modern technology.",
    basePrice: 1178649,
    heroImage: `${HONDA_CDN}/menu/BigWing/xl750-transalp.png`,
    colorVariants: [
      { name: "Ross White", hexCode: "#F0F0F0" },
      { name: "Matt Ballistic Black Metallic", hexCode: "#2A2A2A" },
      { name: "Candy Energy Orange", hexCode: "#E87722" },
    ],
    specifications: [
      { key: "Engine", value: "755 cc, Liquid-cooled, 4-Stroke, SOHC, Parallel-Twin" },
      { key: "Max Power", value: "67.5 kW @ 9500 rpm" },
      { key: "Max Torque", value: "75 Nm @ 7250 rpm" },
      { key: "Fuel Tank", value: "16.9 L" },
      { key: "Kerb Weight", value: "208 kg" },
      { key: "Transmission", value: "6-Speed" },
      { key: "Brakes (Front)", value: "Dual 310mm Discs" },
      { key: "Brakes (Rear)", value: "256mm Disc" },
    ],
    features: [
      { title: "5\" TFT Touch Display" },
      { title: "5 Riding Modes" },
      { title: "Honda Selectable Torque Control (HSTC)" },
      { title: "Cruise Control" },
      { title: "Wheelie Control & Rear Lift Control" },
    ],
    trims: [],
    sortOrder: 37,
  },
  {
    name: "Gold Wing Tour",
    category: "motorcycle",
    subSegment: "BigWing",
    tagline: "The Ultimate Touring Machine",
    description: "Honda's flagship grand tourer with 6-cylinder boxer engine, DCT and Airbag.",
    basePrice: 4312654,
    heroImage: `${HONDA_CDN}/Goldwing-Tour--New-(1).png`,
    colorVariants: [
      { name: "Candy Ardent Red", hexCode: "#991111" },
      { name: "Pearl Glare White", hexCode: "#F5F5F0" },
      { name: "Mat Jeans Blue Metallic", hexCode: "#3A5A8A" },
    ],
    specifications: [
      { key: "Engine", value: "1833 cc, Liquid-cooled, 4-Stroke, SOHC, Flat-6" },
      { key: "Max Power", value: "93 kW @ 5500 rpm" },
      { key: "Max Torque", value: "170 Nm @ 4500 rpm" },
      { key: "Fuel Tank", value: "21.1 L" },
      { key: "Kerb Weight", value: "367 kg" },
      { key: "Transmission", value: "7-Speed DCT" },
      { key: "Brakes (Front)", value: "Dual 320mm Discs" },
      { key: "Brakes (Rear)", value: "316mm Disc" },
    ],
    features: [
      { title: "7\" TFT Display with Apple CarPlay" },
      { title: "Dual Clutch Transmission (DCT)" },
      { title: "Electronically Adjustable Suspension" },
      { title: "Hill Start Assist" },
      { title: "Heated Seats & Grips" },
    ],
    trims: [],
    sortOrder: 38,
  },
];
